### ISSUE TITLE
new run_backend.sh breaks standard use

### ISSUE THREAD

**Issue by saulgoldsaga** [SAGARobotics/rasberry_perception#10]
`roslaunch rasberry_perception gripper.launch backend:=detectron2`
fails because of [run_backend.sh](https://github.com/SAGARobotics/rasberry_perception/blob/086382e2981ddd84baf7aa2b93dde0f807d6b12a/scripts/run_backend.sh)
#
Error message: `No such service: detectron2
`
reverting the file to previous commit fixes it. Can you provide instructions on what the changes are for, or what I need to change to make it work?

**Comment by nikostsagk** [comment]
the gripper.launch is obsolete. Both server and client, regardless of backend should start with 
```
roslaunch rasberry_perception detector.launch service_name:="gripper_perception"
```

I Haven't tidy yet the launch files, I would recommend launching separately server and client using:

- For server:
```
bash scripts/run_backend.sh gripper_perception
```
- For client: 
```
# Comment in the launch file the first part with the server and then
roslaunch rasberry_perception detector.launch
```

**Comment by nikostsagk** [comment]
these files are now obsolete
