### ISSUE TITLE
Torch 1.7.1+ and CUDA 11.1 + Required for RTX 3000 series GPUs (Compute 86)

### ISSUE THREAD

**Issue by rjwb1** [SAGARobotics/rasberry_perception#26]
I think this should be possible to merge and should be backwards compatible with old hardware. Does anyone have any objections to this? 

Current CUDA: 10.2
Current Torch 1.6
(detectron2)

**Comment by saulgoldsaga** [comment]
Do you have a PR for this?

**Comment by rjwb1** [comment]
Currently on a separate branch cuda11_1

**Comment by rjwb1** [comment]
Also pushed images for base, detectron2, tensorrt under cuda11_1 tag
